version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  inference-gateway:
    build: ./services/inference-gateway
    env_file: .env
    ports:
      - "4001:4001"
    depends_on:
      - redis
  orchestrator:
    build: ./services/orchestrator
    env_file: .env
    ports:
      - "4002:4002"
    depends_on:
      - redis
      - mongo
      - inference-gateway
  codegen:
    build: ./services/codegen
    env_file: .env
    ports:
      - "4003:4003"
    depends_on:
      - redis
      - minio
  worker:
    build: ./services/worker
    env_file: .env
    ports:
      - "4004:4004"
    depends_on:
      - redis
      - codegen
      - orchestrator
volumes:
  mongo_data:
  minio_data:
