name: Release CLI

on:
  workflow_dispatch:
  push:
    tags:
      - 'cli-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build cross binaries
        run: |
          cd cli
          make cross
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: caps-cli
          path: cli/bin/*
